import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/Header";
import ReduxProvider from "./ReduxProvider";
import SessionWrapper from "./SessionWrapper";
import Script from "next/script";
import Footer from "./components/Home/Footer";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
         <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="beforeInteractive" />
      <body>
        <SessionWrapper>

        <ReduxProvider >
          <Header />

          {children}
          <Footer/>
        </ReduxProvider>
        </SessionWrapper>
       
      </body>
    </html>
  );
}
